/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Connections
         * @description List all configured database connection aliases.
         */
        get: operations["list_connections_api_connections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Schema
         * @description Discover the schema for the active database.
         */
        get: operations["get_schema_api_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/query/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute Query
         * @description Transpile an AST and execute the resulting SQL.
         */
        post: operations["execute_query_api_query_execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Column */
        Column: {
            /** Table */
            table: string;
            /** Column */
            column: string;
            /** Alias */
            alias?: string | null;
        };
        /** ColumnMetadata */
        ColumnMetadata: {
            /** Name */
            name: string;
            /** Data Type */
            data_type: string;
            /** Is Nullable */
            is_nullable: boolean;
            /** Default Value */
            default_value?: string | null;
        };
        /** Condition */
        Condition: {
            /** Column */
            column: string;
            operator: components["schemas"]["Operator"];
            /** Value */
            value: unknown;
            /**
             * Logic
             * @default AND
             */
            logic: string | null;
        };
        /** DatabaseSchema */
        DatabaseSchema: {
            /** Tables */
            tables: components["schemas"]["TableMetadata"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Join */
        Join: {
            type: components["schemas"]["JoinType"];
            /** Table */
            table: string;
            /** On */
            on: string | components["schemas"]["JoinCondition"];
        };
        /** JoinCondition */
        JoinCondition: {
            /** Left */
            left: string;
            /** Right */
            right: string;
        };
        /**
         * JoinType
         * @enum {string}
         */
        JoinType: "INNER" | "LEFT" | "RIGHT" | "FULL";
        /**
         * Operator
         * @enum {string}
         */
        Operator: "=" | "!=" | ">" | "<" | ">=" | "<=" | "LIKE" | "IN";
        /** QueryAST */
        QueryAST: {
            /** Select */
            select: components["schemas"]["Column"][];
            /** From */
            from: string;
            /**
             * Joins
             * @default []
             */
            joins: components["schemas"]["Join"][] | null;
            /**
             * Where
             * @default []
             */
            where: components["schemas"]["Condition"][] | null;
            /**
             * Sorts
             * @default []
             */
            sorts: components["schemas"]["SortCondition"][] | null;
            /**
             * Limit
             * @default 100
             */
            limit: number | null;
        };
        /** SortCondition */
        SortCondition: {
            /** Column */
            column: string;
            /**
             * Direction
             * @default ASC
             */
            direction: string;
        };
        /** TableMetadata */
        TableMetadata: {
            /** Name */
            name: string;
            /** Columns */
            columns: components["schemas"]["ColumnMetadata"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_connections_api_connections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_schema_api_schema_get: {
        parameters: {
            query?: never;
            header?: {
                "x-database-alias"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatabaseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_query_api_query_execute_post: {
        parameters: {
            query?: never;
            header?: {
                "x-database-alias"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryAST"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
